export const GRID_SIZE = 12;
export const WORD_COUNT_PER_LEVEL = 10;
export const GAME_DURATION_SECONDS = 60;

export const PRIMARY_ORANGE = '#F5750D';

export const THEME_COLORS = [
  'bg-red-500',
  'bg-blue-500',
  'bg-green-500',
  'bg-purple-500',
  'bg-pink-500',
  'bg-teal-500',
];

export const SPANISH_WORDS = [
  "ABONO", "ACERO", "ADAPTADOR", "ADHESIVO", "AIREADOR", "AISLANTE", "ALACENA",
  "ALAMBRE", "ALFOMBRA", "ALICATE", "ANILLO", "ARBOL", "ARBUSTO", "ARENA",
  "ARMARIO", "ARNES", "AZULEJO", "BALCON", "BALDOSA", "BANCO", "BARBIJOS",
  "BARNIZ", "BASE", "BATERIA", "BATIDORA", "BATIENTE", "BEGONIA", "BIDET",
  "BISAGRA", "BOBINA", "BODEGA", "BOMBA", "BOMBILLA", "BONSAI", "BOTAS",
  "BOTIQUIN", "BRIDA", "BROCA", "BROCHA", "BURLETE", "BUTACA", "CABECERA",
  "CABLE", "CACTUS", "CAJA", "CAJON", "CAL", "CAMA", "CAMPANA", "CANASTA",
  "CANDADO", "CAPACITOR", "CARETA", "CARPETA", "CASCO", "CASCOS", "CELOSIA",
  "CEMENTO", "CEPILLO", "CERAMICA", "CERRADURA", "CERROJO", "CESPED", "CESTA",
  "CHALECO", "CHAPA", "CHIMENEA", "CINTA", "CINTURON", "CLAVO", "CLOSET",
  "COBRE", "CODERAS", "CODO", "COLOR", "COMODA", "CONECTOR", "CONGELAR",
  "COPLE", "CORREDIZO", "CORTINA", "CRISTAL", "CUTTER", "DALIA", "DELANTAL",
  "DIFUSOR", "DOSIFICAR", "EMPAQUE", "ENCHAPE", "ENCHUFE", "ENGRANE",
  "ESCRITOR", "ESMALTE", "ESPATULA", "ESPEJO", "ESPONJA", "ESTANTE", "ESTUCHE",
  "ESTUCO", "ESTUFA", "EXTENSOR", "FAROL", "FILTRO", "FLOR", "FOCO", "FOTOCELDA",
  "FUSIBLE", "GAFAS", "GANCHOS", "GAVETA", "GRANITO", "GRAPAS", "GRAVA",
  "GRIFO", "GUANTES", "HELECHO", "HERRERO", "HIDRO", "HORNO", "HUERTO",
  "ILUMINAR", "JABON", "JARDIN", "JAZMIN", "JUNTA", "LADRILLO", "LAMINADO",
  "LAMPARA", "LATEX", "LAVABLE", "LAVABO", "LAVADORA", "LAVAMANOS", "LAVANDA",
  "LED", "LIBRERO", "LICUADORA", "LIJA", "LIMA", "LINOLEO", "LLAVE", "LOSETA",
  "LUMINARIA", "LUZ", "MACETA", "MADERA", "MAMPARA", "MANGAS", "MANGUERA",
  "MANIJA", "MARCO", "MARMOL", "MARTILLO", "MECEDORA", "MESA", "METRO",
  "MICROOND", "MINISPLIT", "MODULAR", "MORTERO", "MOSAICO", "MOSQUITERO",
  "NIPLE", "NIVELADOR", "OREJERAS", "ORQUIDEA", "OVEROL", "OXIDO", "PALMERAS",
  "PANEL", "PANTALLA", "PEGAMENTO", "PERCHA", "PERCHERO", "PERGOLA", "PERNO",
  "PERSIANA", "PETUNIA", "PICAPORTE", "PINTOR", "PINTURA", "PISO", "PISTOLA",
  "PIVOTE", "PLAFON", "PLANCHA", "PLASTICO", "PLOMERO", "POMO", "POSTIGO",
  "PRIMER", "PROTECTOR", "PUERTA", "PULIDO", "RADIADOR", "RECAMARA",
  "RECIBIDOR", "REFLECTOR", "REGADERA", "REGULADOR", "REJA", "REJILLA", "RELOJ",
  "REMACHE", "REPISA", "RESINA", "RESISTOR", "REVESTIR", "RIEGO", "RIEL",
  "ROCIADOR", "RODILLERA", "RODILLO", "ROPERO", "ROSAL", "ROSCA", "SANITARIO",
  "SECADOR", "SECADORA", "SELLADOR", "SEMILLA", "SENSOR", "SERRUCHO", "SETO",
  "SIERRA", "SIFON", "SILLA", "SOFA", "SOLDADOR", "SOPORTE", "SPOT", "SUELO",
  "TABIQUE", "TABLERO", "TABURETE", "TALADRO", "TAPETE", "TAPON", "TARIMA",
  "TARUGO", "TAZA", "TECHO", "TEFLON", "TEJA", "TEMPERA", "TERMINAL", "TIERRA",
  "TINACO", "TOALLA", "TOALLERO", "TOCADOR", "TORNILLO", "TOSTADOR", "TRAGALUZ",
  "TRINCHAR", "TUBERIA", "TUERCA", "TULIPAN", "UMBRAL", "UNIFORME", "UNION",
  "VALVULA", "VENTANA", "VENTILAD", "VERNIZ", "VIDRIO", "VINILO", "VISOR",
  "VITRINA", "YESERO", "YESO", "CONSTRUIR", "REPARAR", "LIMPIAR", "PULIR",
  "RENOVAR", "REEMPLAZAR", "AMPLIAR", "DECORAR", "GUARDAR"
];